captureDirectory: capturing
completeDirectory: captured
tui: false
streamerSubdir: true
scanInterval: 300
autoConvertType: mp4
keepTsFile: false
streamlink: false
proxyenable: false
proxyserver: socks5://127.0.0.1:1080
minByteSize: 0
maxByteSize: 0
dateFormat: YYYYMMDD_HHmmss
debug: false
debugrecorder: false
logenable: true
logappend: true
logshown: true
listshown: true
namecolor: magenta
statecolor: yellow
offlinecolor: blue
filecolor: green
timecolor: grey
sitecolor: green
debugcolor: yellow
errorcolor: red
includeSiteInFile: false
includeSiteInDir: false
enableMFC: false
enableCB: true
enableTwitch: true
enableMixer: true
enableBonga: false
enableCamsoda: false
enableFC2: false
