tui: false
enable:
  MFC: true
  CB: true
  Twitch: true
  Mixer: true
  Bonga: false
  FC2: false
recording:
  autoConvertType: mp4
  captureDirectory: capturing
  completeDirectory: captured
  dateFormat: YYYYMMDD_HHmmss
  includeSiteInFile: false
  includeSiteInDir: false
  streamerSubdir: true
  streamlink: false
  keepTsFile: false
  minSize: 0
  maxSize: 0
log:
  enable: true
  append: true
  shown: true
list:
  shown: true
colors:
  name: magenta
  state: yellow
  offline: blue
  file: green
  time: grey
  site: green
  debug: yellow
  error: red
proxy:
  enable: false
  server: socks5://127.0.0.1:1080
debug:
  log: false
  recorder: false
  errortrace: false
